# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(942, 507)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSua = QtWidgets.QPushButton(self.widget_3)
        self.btnSua.setObjectName("btnSua")
        self.gridLayout.addWidget(self.btnSua, 2, 6, 1, 1)
        self.btnThem = QtWidgets.QPushButton(self.widget_3)
        self.btnThem.setObjectName("btnThem")
        self.gridLayout.addWidget(self.btnThem, 0, 6, 1, 1)
        self.btnXoa = QtWidgets.QPushButton(self.widget_3)
        self.btnXoa.setObjectName("btnXoa")
        self.gridLayout.addWidget(self.btnXoa, 3, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.txtTenKhachHang = QtWidgets.QLineEdit(self.widget_3)
        self.txtTenKhachHang.setObjectName("txtTenKhachHang")
        self.gridLayout.addWidget(self.txtTenKhachHang, 0, 1, 1, 1)
        self.txtSoDienThoai = QtWidgets.QLineEdit(self.widget_3)
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.gridLayout.addWidget(self.txtSoDienThoai, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnSua.setText(_translate("Form", "Sửa"))
        self.btnThem.setText(_translate("Form", "Thêm"))
        self.btnXoa.setText(_translate("Form", "Xóa"))
        self.label_3.setText(_translate("Form", "Tên khách hàng:"))
        self.label_2.setText(_translate("Form", "Số điện thoại:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
